server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuyleangIng/config-server.git
          default-label: main
          clone-on-start: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/