# spring:
#   config:
#     import: optional:configserver:http://localhost:8888
#   application:
#     name: user-service
#   datasource:
#     url: ${SPRING_DATASOURCE_URL}
#     username: ${SPRING_DATASOURCE_USERNAME}
#     password: ${SPRING_DATASOURCE_PASSWORD}
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# server:
#   port: 8081
#spring:
#  application:
#    name: user-service
#  profiles:
#    active: dev

#spring:
#  application:
#    name: user-service
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: true
#
#---
spring:
 config:
   activate:
     on-profile: dev
   import: optional:configserver:http://localhost:8888
 datasource:
   url: jdbc:postgresql://localhost:5432/userdb
   username: admin
   password: admin@123
 jpa:
   hibernate:
     ddl-auto: update
server:
 port: 8081
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: admin
#    password: admin@123
#  jpa:
#    hibernate:
#      ddl-auto: validate
#server:
#  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/